







	



.build/atmega328/ArduinoIRremote/IRremote.d : /usr/share/arduino/libraries/ArduinoIRremote/IRremote.cpp
	@mkdir -p .build/atmega328/ArduinoIRremote
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/capsense -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/ArduinoIRremote -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility  -MM $^ > $@
	
	@printf ".build/atmega328/ArduinoIRremote/IRremote.d .build/atmega328/ArduinoIRremote/" | cat - $@ > $@~ && mv $@~ $@



.build/atmega328/ArduinoIRremote/dependencies.d : .build/atmega328/ArduinoIRremote/IRremote.d
	@echo [96mScanning dependencies of ArduinoIRremote[0m
	@mkdir -p .build/atmega328/ArduinoIRremote
	@cat $^ > $@;

all : .build/atmega328/ArduinoIRremote/dependencies.d
	@true

